In [1]:
import numpy as np

In [8]:
# 넘파이의 기반 데이터 타입은 ndarray
# ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 연산을 수행할 수 있다.

# 넘파이 array() 함수 : 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능 수행
# 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원 알 수 있다.

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
print(f"array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원")
# 리스트 []는 1차원이고, 리스트의 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있다.

array1: 1차원, array2: 2차원, array3: 2차원


In [14]:
# ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.
# 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없다.
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

print('-'*50)

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
print('모두 문자열 값으로 변환됨')

print('-'*50)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
print('모두 float형으로 변환됨')

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
--------------------------------------------------
['1' '2' 'test'] <U11
모두 문자열 값으로 변환됨
--------------------------------------------------
[1. 2. 3.] float64
모두 float형으로 변환됨


In [18]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

print('-'*50)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

print('-'*50)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
--------------------------------------------------
[1 2 3] int32
--------------------------------------------------
[1 2 3] int32


* arange(), zeros(), ones()

In [19]:
# arange(), zeros(), ones()

# arange()는 array를 range()로 표현하는 것이다.
# 0부터 함수 인자 값 -1 까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다.

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

print('-'*50)

# zeros()는 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다.
# ones()는 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다.
# 함수 인자로 dtype 정해주지 않으면 default 로 float64 형의 데이터로 ndarray 채운다.

zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

print('-'*50)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
--------------------------------------------------
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* reshape()

In [22]:
# resahpe() 메서드는 ndarray를 특정 차원 및 크기로 변환

array1 = np.arange(10)
print('array1:\n', array1)

print('-'*50)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

print('-'*50)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------------------------------------
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
array1.reshape(4, 3)
# 지정된 사이즈로 변경이 불가능하면 오류 발생!

ValueError: cannot reshape array of size 10 into shape (4,3)

In [24]:
# reshape() 효율적으로 사용하는 경우 : -1 적용
# -1 인자 사용하면 원래 ndarray 와 호환되는 새로운 shape로 변환해준다.

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [29]:
# -1 인자는 reshape(-1, 1)와 같은 형태로 자주 사용한다.
# reshape(-1, 1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 한 개의 컬럼을 가진 ndarray로 변환됨을 보장한다.
# 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray 형태를 통일해 유용하게 사용할 수 있다.


# tolist() 메서드는 리스트 자료형으로 변환할 수 있다. 시각적으로 더 이해하기 쉬울 수 있음

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

print('-'*50)

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

print('-'*50)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
--------------------------------------------------
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
--------------------------------------------------
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


* 넘파이의 ndarray의 데이터 세트 선택하기 - Indexing

1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.
2. 슬라이싱
3. 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.
4. 불린 인덱싱 : 특정 조건에 해당하는지 여부인 True/False값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다.

In [36]:
# 단일 값 추출

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1:', array1)

print('-'*50)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번 째 값:', array1[-2])

print('-'*50)

# 단일 인덱스 이용하여 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

print('-'*50)

# 다차원 ndarray에서 단일 값 추출
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('-'*50)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

array1: [1 2 3 4 5 6 7 8 9]
--------------------------------------------------
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 맨 뒤에서 두번 째 값: 8
--------------------------------------------------
array1: [9 2 3 4 5 6 7 8 0]
--------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [40]:
# 슬라이싱

array1 = np.arange(1, 10)
array3 = array1[:3]
print(array3)
print(type(array3))

print('-'*50)

# 2차원 ndarray 슬라이싱
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[:2, :2])
print('array2d[1:3, :3] \n', array2d[1:3, :3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

[1 2 3]
<class 'numpy.ndarray'>
--------------------------------------------------
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, :3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [41]:
# 팬시 인덱싱

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], :2]
print('array2d[[0, 1], :2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], :2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [45]:
# 불린 인덱싱

array1d = np.arange(1, 10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d > 5

print('-'*50)

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

print('-'*50)

indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
--------------------------------------------------
불린 인덱스로 필터링 결과: [6 7 8 9]
--------------------------------------------------
일반 인덱스로 필터링 결과: [6 7 8 9]


* 행렬의 정렬 - sort()와 argsort()

In [51]:
# 넘파이의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬자체에서 sort()를 호출하는 방식이있다.
# np.sort()는 '원 행렬은 그대로 유지한 채' 원 행렬의 정렬된 행렬을 반환
# ndarray.sort()는 '원 행렬 자체를 정렬한 형태'로 변환하며 반환 값은 None

org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)

# ndarray.sort()
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [47]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬 : ', sort_array1_desc)

내림차순 정렬 :  [9 5 3 1]


In [48]:
# 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향 또는 컬럼 방향으로 정렬 수행 가능

array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [52]:
# 정렬된 행렬의 인덱스 반환

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

print('-'*50)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
--------------------------------------------------
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [53]:
# argsort()의 다양한 활용

name_array = np.array(['John', 'Mike', 'Sarah', 'kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'kate']


* 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [54]:
# 행렬 내적
# 행렬 곱으로 두 행렬 A, B의 내적은 np.dot()를 이용해 계산
# 왼쪽 행렬의 로우와 오른쪽 행렬의 컬럼의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값이다.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10], 
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [55]:
# 전치 행렬
# 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬

A = np.array([[1, 2], 
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
